### ISSUE TITLE
Change sequence of deployment script: set env vars -> compile

### ISSUE THREAD

**Issue by vbaranov** [poanetwork/blockscout-terraform#132] opened 2019-08-16 13:39 UTC
Some ENV vars are used in compilation time (see https://github.com/poanetwork/blockscout/pull/2577 for the reference). Thus, the correct sequence in the deployment script should be: set env vars -> compile (and not vise-versa)

**Comment by ArseniiPetrovich** [comment] 2019-09-03 13:16
Looks like the issue is already fixed in master with the recent PR, closing for now.
@vbaranov

**Closed by ArseniiPetrovich** 2019-09-03 13:16 UTC

**Comment by vbaranov** [comment] 2019-09-04 15:34
@ArseniiPetrovich could you provide the code lines where compilation and env vars set does take place? I already tried to deploy some instances a while ago from master and the issue that misorder causes didn't resolve.

**Comment by ArseniiPetrovich** [comment] 2019-09-05 13:41
Sure, @vbaranov 
Please, check https://github.com/poanetwork/blockscout-terraform/blob/e2e8326940a1a712edf7298505168a0a529244db/roles/main_software/tasks/main.yml#L133
Also I tried it manually and it seems to be working for me.

**Comment by ayrat555** [comment] 2019-09-11 09:38
maybe we can `clean` here https://github.com/poanetwork/blockscout-terraform/blob/e2e8326940a1a712edf7298505168a0a529244db/roles/main_software/tasks/main.yml#L135

**Comment by ArseniiPetrovich** [comment] 2019-09-11 09:46
@ayrat555 I don't think this is necessary. Deployment scripts delete and re-pull BS repo each time we run the deployment process unless the `skip_fetch` is not set to `true`
